version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json
  app:
    build: .
    container_name: nodejs-keycloak-api
    volumes:
      - .:/home/node/app
    ports:
      - 3005:3000
